### ISSUE TITLE
CoffeeScript support

### ISSUE THREAD

**Issue by mreq** [syko/SublimeLogMagic#1]
Any idea how much work would that be? Only the matching part would have to be modified to allow the use of the `nonParen syntax` for functions. There are also some minor whitespace issues.

I might attempt a PR if you think Coffee support is feasible.

**Comment by syko** [comment]
It's something I would be interested in having as well. I'll take a look to see how bad it would be to implement that.

**Comment by syko** [comment]
CoffeeScript support has landed in v1.1.0 (will appear in Package Control shortly)

**Comment by mreq** [comment]
That's amazing, thanks!
