### ISSUE TITLE
Suggestion: Filename with line number

### ISSUE THREAD

**Issue by accidentallyc** [syko/SublimeLogMagic#10]
**TLDR;**
can add filename + line number in the print statement?

**Why**
Incase we forget to delete these statements, we have more clarity as to where the log line is located. 

**Not TLDR;**
Hey there, i was about to convert my atom plugin , [line-to-console](https://atom.io/packages/atom-line-to-console). To sublime but then i found this package, and i thought that i would rather just see if i can contribute instead.

So one of the things, i did in that package was to add the filename + line number in the print/console statement. 

Any thoughts on this suggestion?

**Comment by syko** [comment]
Good idea. Should probably have it configurable probably.
In fact I was thinking of adding a command to remove all `console.log` lines from the file at once. I should actually make an issue of that too.
