### ISSUE TITLE
maintained?

### ISSUE THREAD

**Issue by rchl** [syko/SublimeLogMagic#16]
Since it wasn't updated in 5 years, I wonder if it's worth suggesting some updates or submitting PRs or it's considered abandoned?

I have nothing serious in mind, more like some maintenance.

**Comment by syko** [comment]
Hey,

Since it's still out there I wouldn't want to call it 'abandoned' even though I don't use it myself anymore (I've switched over to vscode for the time being). I'd try and get bugfixes and smaller stuff in but honestly this thing could use a proper rewrite.
